In [1]:
import numpy as np
from sklearn.datasets import load_diabetes
import pandas as pd

In [2]:
x,y = load_diabetes(return_X_y=True)

In [3]:
df = pd.DataFrame(y)
df

0
0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
..     ...
437  178.0
438  104.0
439  132.0
440  220.0
441   57.0

[442 rows x 1 columns]

In [4]:
df1 = pd.DataFrame(x)
df1

0         1         2         3         4         5         6  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

            7         8         9  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [5]:
df = pd.DataFrame(y)
df

0
0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
..     ...
437  178.0
438  104.0
439  132.0
440  220.0
441   57.0

[442 rows x 1 columns]

In [6]:
x.shape

(442, 10)

In [7]:
y.shape

(442,)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test ,y_train, y_test = train_test_split(x,y,test_size = 0.3,random_state=1234,)
# X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [10]:
print(x_train.shape)
print(x_test.shape)

(309, 10)
(133, 10)


In [11]:
print(y_train.shape)
print(y_test.shape)

(309,)
(133,)


In [12]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [13]:
lr.fit(x_train,y_train)

LinearRegression()

In [14]:
y_pred = lr.predict(x_test)

In [15]:
# y_pred.shape
x_test[2]

array([-0.06363517,  0.05068012, -0.07949718, -0.00567042, -0.07174256,
       -0.06644876, -0.01026611, -0.03949338, -0.01811369, -0.05492509])

In [16]:

y_pred[2]

93.88152273403998

In [17]:
from sklearn.metrics import r2_score

In [18]:
r2_score(y_test,y_pred)

0.48913131138579125

In [19]:
lr.coef_

array([ -24.70383385, -280.56147007,  527.46638668,  318.48336765,
       -706.38958625,  412.32549136,   69.86068222,  171.5122585 ,
        753.25249791,   77.53459931])

In [20]:
lr.intercept_

152.38029906632843

# Making our own Linear Regression Class

In [22]:
class MeraLR:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)
        
     #   β=((XT*X)−1) *(XT*y)
        
        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)  # np.linalg.inv : ye only invers kr rha hai
        self.intercept_ = betas[0]            # metrix ka first col intecept banega
        
        self.coef_ = betas[1:]                 # matrix ke first col ko chhodke baki ke col coeficent banenge
        
                                      # yha sb metrix ke form me chal rha hai
    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred
        

In [23]:
lr = MeraLR()

In [24]:
lr.fit(x_train,y_train)

In [25]:
x_train.shape

(309, 10)

In [26]:
np.insert(x_train,0,1,axis=1).shape

(309, 11)

In [27]:
y_pred = lr.predict(x_test)

In [28]:
r2_score(y_test,y_pred)

0.4891313113857919

In [29]:
lr.coef_

array([ -24.70383385, -280.56147007,  527.46638668,  318.48336765,
       -706.38958625,  412.32549136,   69.86068222,  171.5122585 ,
        753.25249791,   77.53459931])

In [30]:
lr.intercept_

152.3802990663284