In [1]:
from sklearn import datasets

In [3]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circl

In [4]:
from sklearn.datasets import fetch_california_housing

In [5]:
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [6]:
housing.keys() # dictionarys key vakues comes

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [7]:
housing["DESCR"] # IT is nothing but a descrbtions

'.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 20640\n\n    :Number of Attributes: 8 numeric, predictive attributes and the target\n\n    :Attribute Information:\n        - MedInc        median income in block group\n        - HouseAge      median house age in block group\n        - AveRooms      average number of rooms per household\n        - AveBedrms     average number of bedrooms per household\n        - Population    block group population\n        - AveOccup      average number of household members\n        - Latitude      block group latitude\n        - Longitude     block group longitude\n\n    :Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000

In [10]:
# make datafream
import pandas as pd
df = pd.DataFrame(housing.data,
                   columns = housing.feature_names) # input data
df["MedHouseVal"] = housing['target']
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [12]:
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [13]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [14]:
df.shape

(20640, 9)

In [17]:
df.dropna(inplace=True) # Drop the Null
df.reset_index(drop=True,
               inplace=True)
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [18]:
df.shape

(20640, 9)

In [19]:
df.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')

In [20]:
df.dtypes

MedInc         float64
HouseAge       float64
AveRooms       float64
AveBedrms      float64
Population     float64
AveOccup       float64
Latitude       float64
Longitude      float64
MedHouseVal    float64
dtype: object

In [21]:
X = df.drop('MedHouseVal',axis=1)
y = df['MedHouseVal']

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,  # Input data
                                                    y,  # output data
                                                    random_state=1234, # it select random samples
                                                    test_size=0.30)   #30 % test data hai means 70:30 ka ratio hai


In [28]:
X_train

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
2531   2.8333      37.0  5.561321   0.974057      1060.0  2.500000     39.51   
3802   2.7730      20.0  3.884141   1.207028      2824.0  2.681861     34.20   
9260   1.4511      32.0  4.644689   1.036630       549.0  2.010989     36.96   
9715   2.8289      38.0  4.438148   1.031125      3523.0  2.811652     36.68   
96     2.8345      31.0  3.894915   1.127966      2048.0  1.735593     37.82   
...       ...       ...       ...        ...         ...       ...       ...   
8222   5.0000      21.0  3.062500   0.875000        29.0  1.812500     33.76   
9449   2.7530      14.0  5.789030   1.170886      1153.0  2.432489     37.39   
8471   4.2083      33.0  5.026163   1.151163      1073.0  3.119186     33.91   
17048  6.7058      44.0  6.335430   0.991614      1235.0  2.589099     37.47   
1318   5.4409       4.0  7.853352   1.089385      2429.0  3.392458     37.99   

       Longitude  
2531     -122.20  
3802     -118.43  
9260     -120.07  
9715     -121.67  
96       -122.26  
...          ...  
8222     -118.23  
9449     -119.85  
8471     -118.32  
17048    -122.27  
1318     -121.77  

[14448 rows x 8 columns]

In [29]:
X_test

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
15712  3.6812      52.0  4.848315   1.078652       614.0  1.724719     37.79   
4119   5.5524      52.0  6.129032   1.041935      1842.0  2.970968     34.14   
15725  3.8750      44.0  4.739264   1.024540       561.0  1.720859     37.78   
14616  3.4706      20.0  5.274254   1.033582      1822.0  3.399254     32.80   
13238  7.7234      10.0  8.016901   1.019718      1221.0  3.439437     34.13   
...       ...       ...       ...        ...         ...       ...       ...   
7665   4.1250       5.0  5.734177   1.183544      1453.0  9.196203     33.93   
2196   3.8056      29.0  6.391304   1.060870      1072.0  3.107246     36.83   
18162  6.8753      26.0  6.987288   0.974576      1241.0  2.629237     37.36   
16305  3.5982      15.0  4.462562   0.996672      1520.0  2.529118     38.01   
199    2.6429      52.0  3.746032   1.158730       415.0  3.293651     37.78   

       Longitude  
15712    -122.44  
4119     -118.20  
15725    -122.44  
14616    -117.17  
13238    -117.67  
...          ...  
7665     -118.07  
2196     -119.91  
18162    -122.04  
16305    -121.35  
199      -122.23  

[6192 rows x 8 columns]

In [31]:
y_train

2531     0.697
3802     1.405
9260     0.652
9715     1.683
96       1.838
         ...  
8222     0.875
9449     1.111
8471     1.805
17048    4.959
1318     2.051
Name: MedHouseVal, Length: 14448, dtype: float64

In [33]:
y_test

15712    5.000
4119     2.939
15725    4.125
14616    1.576
13238    3.041
         ...  
7665     1.719
2196     1.654
18162    4.030
16305    0.944
199      0.713
Name: MedHouseVal, Length: 6192, dtype: float64

In [34]:
print("the shape of data frame is:",df.shape)
print("the shape of X_train is:",X_train.shape)
print("the shape of X_test frame is:",X_test.shape)
print("the shape of y_train frame is:",y_train.shape)
print("the shape of y_test frame is:",y_test.shape)

the shape of data frame is: (20640, 9)
the shape of X_train is: (14448, 8)
the shape of X_test frame is: (6192, 8)
the shape of y_train frame is: (14448,)
the shape of y_test frame is: (6192,)


In [40]:
# from sklearn.linear_model import LinearRegression
# LR=LinearRegression()
# LR.fit(X_train,y_train)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [42]:
# Model predictions happens X_test
y_predictions=model.predict(X_test)
y_predictions

array([2.60474013, 2.94398545, 2.59138626, ..., 3.44254726, 1.63598042,
       2.24182191])

In [44]:
y_predictions.shape

(6192,)

In [45]:
y_predictions

array([2.60474013, 2.94398545, 2.59138626, ..., 3.44254726, 1.63598042,
       2.24182191])

In [46]:
y_test.shape,y_predictions.shape

((6192,), (6192,))

In [47]:
X_test

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
15712  3.6812      52.0  4.848315   1.078652       614.0  1.724719     37.79   
4119   5.5524      52.0  6.129032   1.041935      1842.0  2.970968     34.14   
15725  3.8750      44.0  4.739264   1.024540       561.0  1.720859     37.78   
14616  3.4706      20.0  5.274254   1.033582      1822.0  3.399254     32.80   
13238  7.7234      10.0  8.016901   1.019718      1221.0  3.439437     34.13   
...       ...       ...       ...        ...         ...       ...       ...   
7665   4.1250       5.0  5.734177   1.183544      1453.0  9.196203     33.93   
2196   3.8056      29.0  6.391304   1.060870      1072.0  3.107246     36.83   
18162  6.8753      26.0  6.987288   0.974576      1241.0  2.629237     37.36   
16305  3.5982      15.0  4.462562   0.996672      1520.0  2.529118     38.01   
199    2.6429      52.0  3.746032   1.158730       415.0  3.293651     37.78   

       Longitude  
15712    -122.44  
4119     -118.20  
15725    -122.44  
14616    -117.17  
13238    -117.67  
...          ...  
7665     -118.07  
2196     -119.91  
18162    -122.04  
16305    -121.35  
199      -122.23  

[6192 rows x 8 columns]

In [48]:
X_test.shape,y_test.shape,y_predictions.shape

((6192, 8), (6192,), (6192,))

In [49]:
test_data=X_test
test_data['y_actual']=y_test
test_data['y_predictions']=y_predictions
test_data   

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
15712  3.6812      52.0  4.848315   1.078652       614.0  1.724719     37.79   
4119   5.5524      52.0  6.129032   1.041935      1842.0  2.970968     34.14   
15725  3.8750      44.0  4.739264   1.024540       561.0  1.720859     37.78   
14616  3.4706      20.0  5.274254   1.033582      1822.0  3.399254     32.80   
13238  7.7234      10.0  8.016901   1.019718      1221.0  3.439437     34.13   
...       ...       ...       ...        ...         ...       ...       ...   
7665   4.1250       5.0  5.734177   1.183544      1453.0  9.196203     33.93   
2196   3.8056      29.0  6.391304   1.060870      1072.0  3.107246     36.83   
18162  6.8753      26.0  6.987288   0.974576      1241.0  2.629237     37.36   
16305  3.5982      15.0  4.462562   0.996672      1520.0  2.529118     38.01   
199    2.6429      52.0  3.746032   1.158730       415.0  3.293651     37.78   

       Longitude  y_actual  y_predictions  
15712    -122.44     5.000       2.604740  
4119     -118.20     2.939       2.943985  
15725    -122.44     4.125       2.591386  
14616    -117.17     1.576       1.920864  
13238    -117.67     3.041       3.040696  
...          ...       ...            ...  
7665     -118.07     1.719       2.017527  
2196     -119.91     1.654       1.554616  
18162    -122.04     4.030       3.442547  
16305    -121.35     0.944       1.635980  
199      -122.23     0.713       2.241822  

[6192 rows x 10 columns]

In [50]:
print(y_test.values[:5])  # float 5. means 5.0
print(y_predictions[:5])

[5.    2.939 4.125 1.576 3.041]
[2.60474013 2.94398545 2.59138626 1.92086396 3.04069604]


In [51]:
# RMSE
# MSE
# MAE
# R-square

from sklearn.metrics import r2_score,mean_squared_error

R2=r2_score(y_test,y_predictions)

MSE=mean_squared_error(y_test,y_predictions)
#MSE**(1/2)

RMSE=np.sqrt(MSE)
#accuracy_score(y_test,y_predictions) # it is a regression tech

print("R-sqaure:",R2)
print("MSE:",MSE)
print("RMSE:",RMSE)

R-sqaure: 0.6017428753930179
MSE: 0.530721223906788
RMSE: 0.7285061591412855


In [52]:
from statsmodels.api import OLS
OLS(y_train,X_train).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:            MedHouseVal   R-squared (uncentered):                   0.893
Model:                            OLS   Adj. R-squared (uncentered):              0.893
Method:                 Least Squares   F-statistic:                          1.510e+04
Date:                Wed, 17 Apr 2024   Prob (F-statistic):                        0.00
Time:                        11:01:06   Log-Likelihood:                         -16788.
No. Observations:               14448   AIC:                                  3.359e+04
Df Residuals:                   14440   BIC:                                  3.365e+04
Df Model:                           8                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
MedInc         0.5179      0.005    100.878      0.000       0.508       0.528
HouseAge       0.0155      0.001     27.974      0.000       0.014       0.017
AveRooms      -0.1949      0.008    -25.913      0.000      -0.210      -0.180
AveBedrms      0.9094      0.037     24.255      0.000       0.836       0.983
Population   7.73e-06   6.11e-06      1.265      0.206   -4.25e-06    1.97e-05
AveOccup      -0.0043      0.001     -7.527      0.000      -0.005      -0.003
Latitude      -0.0615      0.004    -14.453      0.000      -0.070      -0.053
Longitude     -0.0157      0.001    -11.562      0.000      -0.018      -0.013
==============================================================================
Omnibus:                     2759.873   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7652.688
Skew:                           1.020   Prob(JB):                         0.00
Kurtosis:                       5.924   Cond. No.                     1.08e+04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.08e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [56]:
import pickle
pickle.dump(model,
            open('fetch_california_housing_dataset','wb'))

#Model name=LR
#In which name the model is saving: linear_wine_model
# extenstion:.pkl
# wb: write in bytes

In [57]:
# Loading model to compare the results
file = pickle.load(open('fetch_california_housing_dataset','rb'))
file

LinearRegression()

In [63]:
file.predict([[40,2,3,4,.01,6,4,0]])

array([-17.78968329])

In [64]:
X_test

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
15712  3.6812      52.0  4.848315   1.078652       614.0  1.724719     37.79   
4119   5.5524      52.0  6.129032   1.041935      1842.0  2.970968     34.14   
15725  3.8750      44.0  4.739264   1.024540       561.0  1.720859     37.78   
14616  3.4706      20.0  5.274254   1.033582      1822.0  3.399254     32.80   
13238  7.7234      10.0  8.016901   1.019718      1221.0  3.439437     34.13   
...       ...       ...       ...        ...         ...       ...       ...   
7665   4.1250       5.0  5.734177   1.183544      1453.0  9.196203     33.93   
2196   3.8056      29.0  6.391304   1.060870      1072.0  3.107246     36.83   
18162  6.8753      26.0  6.987288   0.974576      1241.0  2.629237     37.36   
16305  3.5982      15.0  4.462562   0.996672      1520.0  2.529118     38.01   
199    2.6429      52.0  3.746032   1.158730       415.0  3.293651     37.78   

       Longitude  y_actual  y_predictions  
15712    -122.44     5.000       2.604740  
4119     -118.20     2.939       2.943985  
15725    -122.44     4.125       2.591386  
14616    -117.17     1.576       1.920864  
13238    -117.67     3.041       3.040696  
...          ...       ...            ...  
7665     -118.07     1.719       2.017527  
2196     -119.91     1.654       1.554616  
18162    -122.04     4.030       3.442547  
16305    -121.35     0.944       1.635980  
199      -122.23     0.713       2.241822  

[6192 rows x 10 columns]

In [65]:
XX = test_data.drop(['y_predictions','y_actual'],axis=1)
yy = test_data['y_predictions']

In [72]:
from sklearn.model_selection import train_test_split

XX_train, XX_test, yy_train, yy_test = train_test_split(XX,
                                                        yy,
                                                        random_state = 1234,
                                                        test_size = 0.40 )



# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X,  # Input data
#                                                     y,  # output data
#                                                     random_state=1234, # it select random samples
#                                                     test_size=0.30)   #30 % test data hai means 70:30 ka ratio hai


In [73]:
file.predict(XX_test)

array([2.32742916, 2.47113389, 2.59256478, ..., 1.44280037, 2.4354653 ,
       1.87652825])

In [74]:
file.predict(XX_train)

array([1.7737243 , 2.23948521, 1.08029897, ..., 1.98193748, 1.99294246,
       5.41752042])

In [75]:
yy_train

3646     1.773724
16623    2.239485
11886    1.080299
11523    2.619380
15505    2.479271
           ...   
11120    2.432982
18102    3.206142
14612    1.981937
14337    1.992942
20436    5.417520
Name: y_predictions, Length: 3715, dtype: float64